=== przemub/cysectool/doc/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://przemub.pl/schemas/visualiser.json",
  "title": "Model",
  "description": "A model",
  "type": "object",
  "required": ["name", "controls", "vertices", "edges"],
  "properties": {
    "name": {
      "description": "Name of the schema",
      "type": "string"
    },
    "controls": {
      "description": "Define available controls",
      "patternProperties": {
        "[A-z0-9]+": {
          "description": "A description of a control",
          "properties": {
            "name": {
              "description": "Name of the control",
              "type": "string"
            },
            "level_name": {
              "description": "Names of the levels of the control",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "cost": {
              "description": "Costs of the levels of the control",
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "ind_cost": {
              "description": "Individual costs of the levels of the control",
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "flow": {
              "description": "Flows of the levels of the control",
              "type": "array",
              "items": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
              }
            }
          },
          "required": ["name", "level_name", "cost", "ind_cost", "flow"]
        }
      }
    },
    "vertices": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "Name of the state"
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["source", "target", "vulnerability"],
        "properties": {
          "source": {
            "type": "integer"
          },
          "target": {
            "type": "integer"
          },
          "default_flow": {
            "type": "number"
          },
          "vulnerability": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "controls": {
                "type": "object",
                "patternProperties": {
                  "[A-z0-9]+": {
                    "type": "object",
                    "properties": {
                      "flow": {
                        "type": "number"
                      },
                      "max_flow": {
                        "type": "number"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== przemub/cysectool/doc/templates/2_ToyModel.json
{
  "name": "ToyModel",
  "controls": {
    "c1": {
      "name": "c1",
      "level_name": [
        "c1 1"
      ],
      "cost": [
        1
      ],
      "ind_cost": [
        1
      ],
      "flow": [
        0.5
      ]
    },
    "c2": {
      "name": "c2",
      "level_name": [
        "c2 1"
      ],
      "cost": [
        1
      ],
      "ind_cost": [
        1
      ],
      "flow": [
        0.2
      ]
    },
    "c3": {
      "name": "c3",
      "level_name": [
        "c3 1"
      ],
      "cost": [
        1
      ],
      "ind_cost": [
        1
      ],
      "flow": [
        0.1
      ]
    },
    "c4": {
      "name": "c4",
      "level_name": [
        "c4 1"
      ],
      "cost": [
        1
      ],
      "ind_cost": [
        1
      ],
      "flow": [
        0.2
      ]
    }
  },
  "vertices": [
    "0",
    "1",
    "2",
    "3"
  ],
  "edges": [
    {
      "source": 0,
      "target": 3,
      "default_flow": 1,
      "vulnerability": {
        "name": "v03",
        "controls": {
          "c3": {}
        }
      }
    },
    {
      "source": 0,
      "target": 1,
      "default_flow": 1,
      "vulnerability": {
        "name": "v01",
        "controls": {
          "c1": {}
        }
      }
    },
    {
      "source": 0,
      "target": 2,
      "default_flow": 1,
      "vulnerability": {
        "name": "v02",
        "controls": {
          "c2": {}
        }
      }
    },
    {
      "source": 1,
      "target": 2,
      "default_flow": 1,
      "vulnerability": {
        "name": "v12",
        "controls": {
          "c3": {},
          "c4": {}
        }
      }
    },
    {
      "source": 1,
      "target": 3,
      "default_flow": 1,
      "vulnerability": {
        "name": "v13",
        "controls": {
          "c2": {}
        }
      }
    },
    {
      "source": 2,
      "target": 3,
      "default_flow": 1,
      "vulnerability": {
        "name": "v23",
        "controls": {
          "c1": {},
          "c4": {}
        }
      }
    }
  ]
}

=== przemub/cysectool/doc/default.json
{
  "name": "Sample",
  "controls": {
    "Sc": {
      "name": "Secure configuration",
      "level_name": ["up-to-date software", "patching", "whitelisting"],
      "cost": [1, 3, 4],
      "ind_cost": [1, 1, 6],
      "flow": [0.4, 0.12, 0.1]
    },
    "N1": {
      "name": "Network security (external)",
      "level_name": ["firewall", "traffic monitoring", "in-depth packet inspection"],
      "cost": [1, 4, 7],
      "ind_cost": [4, 5, 6],
      "flow": [0.3, 0.2, 0.1]
    },
    "N2": {
      "name": "Network security (internal)",
      "level_name": ["firewall", "traffic monitoring", "in-depth packet inspection"],
      "cost": [2, 5, 8],
      "ind_cost": [3, 4, 5],
      "flow": [0.3, 0.2, 0.1]
    },
    "Ed": {
      "name": "User education",
      "level_name": ["basic training", "active simulated social engineering attacks",
              "strongly monitored policies"],
      "cost": [3, 5, 6],
      "ind_cost": [2, 5, 10],
      "flow": [0.5, 0.3, 0.25]
    },
    "Pr": {
      "name": "Processes",
      "level_name": ["inventories", "prompt disabling when users leave"],
      "cost": [2, 3],
      "ind_cost": [2, 4],
      "flow": [0.4, 0.25]
    },
    "A1": {
      "name": "Authentication",
      "level_name": ["strong password policy", "regularly change password"],
      "cost": [1, 4],
      "ind_cost": [3, 7],
      "flow": [0.3, 0.25]
    },
    "A2": {
      "name": "2-factor authentication",
      "level_name": ["2-factor authentication"],
      "cost": [7],
      "ind_cost": [8],
      "flow": [0.05]
    },
    "Am": {
      "name": "Anti-malware",
      "level_name": ["use anti-malware"],
      "cost": [2],
      "ind_cost": [1],
      "flow": [0.2]
    },
    "Ac": {
      "name": "Access control",
      "level_name": ["access control"],
      "cost": [2],
      "ind_cost": [1],
      "flow": [0.1]
    },
    "En": {
      "name": "Encryption",
      "level_name": ["implement encryption"],
      "cost": [3],
      "ind_cost": [2],
      "flow": [0.01]
    }
  },
  "vertices": ["start", "webserver", "in LAN", "credentials", "website", "control", "root"],
  "edges": [
    {
      "source": 0,
      "target": 1,
      "vulnerability": {
        "name": "CVE exploit webserver",
        "controls": {
          "N1": {"flow": 0.8},
          "Sc": {"flow": 2}
        }
      }
    },
    {
      "source": 0,
      "target": 5,
      "default_flow": 0.33333,
      "vulnerability": {
        "name": "CVE exploit direct",
        "controls": {
          "N1": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 0,
      "target": 5,
      "default_flow": 0.33333,
      "vulnerability": {
        "name": "whaling",
        "controls": {
          "N1": {"flow": 4, "max_flow": 0.999},
          "Ed": {}
        }
      }
    },
    {
      "source": 0,
      "target": 3,
      "vulnerability": {
        "name": "phishing",
        "controls": {
          "N1": {},
          "Ed": {}
        }
      }
    },
    {
      "source": 0,
      "target": 3,
      "vulnerability": {
        "name": "compromised external systems",
        "controls": {
          "N1": {"flow": 4, "max_flow": 0.999},
          "Ed": {},
          "Pr": {}
        }
      }
    },
    {
      "source": 0,
      "target": 4,
      "vulnerability": {
        "name": "watering hole",
        "controls": {
          "N1": {"flow": 4, "max_flow": 0.999},
          "Ed": {}
        }
      }
    },
    {
      "source": 1,
      "target": 5,
      "vulnerability": {
        "name": "CVE exploit",
        "controls": {
          "N2": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 1,
      "target": 2,
      "vulnerability": {
        "name": "empty step",
        "controls": {}
      }
    },
    {
      "source": 2,
      "target": 3,
      "vulnerability": {
        "name": "brute force",
        "controls": {
          "N2": {},
          "A1": {}
        }
      }
    },
    {
      "source": 2,
      "target": 3,
      "vulnerability": {
        "name": "sniff traffic",
        "controls": {
          "N2": {},
          "En": {}
        }
      }
    },
    {
      "source": 2,
      "target": 5,
      "vulnerability": {
        "name": "admin exploit",
        "controls": {
          "N2": {},
          "Pr": {}
        }
      }
    },
    {
      "source": 3,
      "target": 5,
      "vulnerability": {
        "name": "log in",
        "controls": {
          "A2": {}
        }
      }
    },
    {
      "source": 4,
      "target": 3,
      "vulnerability": {
        "name": "steal credentials",
        "controls": {
          "Ed": {}
        }
      }
    },
    {
      "source": 4,
      "target": 5,
      "vulnerability": {
        "name": "install malware",
        "controls": {
          "N2": {},
          "Sc": {},
          "Am": {}
        }
      }
    },
    {
      "source": 5,
      "target": 6,
      "vulnerability": {
        "name": "escalate privileges",
        "controls": {
          "Sc": {},
          "A1": {},
		  "Ac": {}
        }
      }
    }
  ]
}

=== przemub/cysectool/doc/templates/4_NCSC.json
{
  "name": "ClearSCADA",
  "controls": {
    "d": {
      "name": "dummy",
      "level_name": [
        "d 1"
      ],
      "cost": [
        1
      ],
      "ind_cost": [
        1
      ],
      "flow": [
        1
      ]
    }
  },
  "vertices": [
    "Internet",
    "Thin client",
    "ViewX",
    "Operational AD",
    "Thick client",
    "Malicious file in OT",
    "Mobile",
    "WebX",
    "Malicious USB",
    "Vendor",
    "Config changed"
  ],
  "edges": [
    {
      "source": 0,
      "target": 1,
      "default_flow": 1,
      "vulnerability": {
        "name": "Phishing client",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 0,
      "target": 6,
      "default_flow": 1,
      "vulnerability": {
        "name": "Phishing mobile",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 6,
      "target": 7,
      "default_flow": 1,
      "vulnerability": {
        "name": "Hijack WebX",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 7,
      "target": 10,
      "default_flow": 1,
      "vulnerability": {
        "name": "Malicious config from WebX",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 1,
      "target": 3,
      "default_flow": 1,
      "vulnerability": {
        "name": "Privilege escalation",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 3,
      "target": 2,
      "default_flow": 1,
      "vulnerability": {
        "name": "Enable ViewX access",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 3,
      "target": 7,
      "default_flow": 1,
      "vulnerability": {
        "name": "Enable admin access",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 4,
      "target": 10,
      "default_flow": 1,
      "vulnerability": {
        "name": "Change config",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 5,
      "target": 10,
      "default_flow": 1,
      "vulnerability": {
        "name": "Change config",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 2,
      "target": 4,
      "default_flow": 1,
      "vulnerability": {
        "name": "Identify a thick client",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 1,
      "target": 5,
      "default_flow": 1,
      "vulnerability": {
        "name": "Upload a malicious file",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 0,
      "target": 8,
      "default_flow": 1,
      "vulnerability": {
        "name": "Knowledge of the system",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 8,
      "target": 5,
      "default_flow": 1,
      "vulnerability": {
        "name": "Social engineering",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 0,
      "target": 9,
      "default_flow": 1,
      "vulnerability": {
        "name": "3rd-party vulnerability",
        "controls": {
          "d": {}
        }
      }
    },
    {
      "source": 9,
      "target": 5,
      "default_flow": 1,
      "vulnerability": {
        "name": "Malicious release",
        "controls": {
          "d": {}
        }
      }
    }
  ]
}

=== przemub/cysectool/doc/templates/1_NIST.json
{
  "name": "NIST",
  "controls": {
    "ScW": {
      "name": "ScW",
      "level_name": ["1"],
      "cost": [1],
      "ind_cost": [1],
      "flow": [0.0000001]
    },
    "ScS": {
      "name": "ScS",
      "level_name": ["1"],
      "cost": [1],
      "ind_cost": [1],
      "flow": [0.0000001]
    },
    "ScDb": {
      "name": "ScDb",
      "level_name": ["1"],
      "cost": [1],
      "ind_cost": [5],
      "flow": [0.0000001]
    },
    "N1": {
      "name": "N1",
      "level_name": ["1"],
      "cost": [1],
      "ind_cost": [1],
      "flow": [0.7]
    },
    "N2": {
      "name": "N2",
      "level_name": ["1"],
      "cost": [1],
      "ind_cost": [1],
      "flow": [0.01]
    },
    "Ed": {
      "name": "Ed",
      "level_name": ["1","2"],
      "cost": [1,1],
      "ind_cost": [1,1],
      "flow": [0.5,0.3]
    }
    
  },
  "vertices": ["start", "10", "14","18", "22","26","30"],
  "edges": [
    {
      "source": 0,
      "target": 1,
      "multiplicity": 0,
      "default_flow": 0.5,
      "vulnerability": {
        "name": "01",
        "controls": {
          "Ed": {}
        }
      }
    },
    {
      "source": 0,
      "target": 1,
      "multiplicity": 1,
      "default_flow": 0.8,
      "vulnerability": {
        "name": "01",
        "controls": {
          "Ed": {}
        }
      }
    },
    {
      "source": 0,
      "target": 3,
      "multiplicity": 0,
      "vulnerability": {
        "name": "03",
        "controls": {
        }
      }
    },
    {
      "source": 1,
      "target": 2,
      "multiplicity": 0,
	  "default_flow": 0.9,
      "vulnerability": {
        "name": "12",
        "controls": {
          "ScW": {},
          "N1":{}
        }
      }
    },
    {
      "source": 2,
      "target": 3,
      "multiplicity": 0,
      "vulnerability": {
        "name": "23",
        "controls": {
        }
      }
    },
    {
      "source": 2,
      "target": 5,
      "multiplicity": 0,
      "vulnerability": {
        "name": "23",
        "controls": {
        "N2":{}
        }
      }
    },
     {
      "source": 4,
      "target": 1,
      "multiplicity": 0,
      "vulnerability": {
        "name": "23",
        "controls": {
        "Ed":{}
        }
      }
    },
     {
      "source": 4,
      "target": 5,
      "multiplicity": 0,
      "vulnerability": {
        "name": "23",
        "controls": {
        }
      }
    },
    {
      "source": 3,
      "target": 4,
      "multiplicity": 0,
      "default_flow": 0.2,
      "vulnerability": {
        "name": "12",
        "controls": {
          "ScS": {},
          "Ed": {},
          "N2":{}
        }
      }      
      },   
      {
      "source": 5,
      "target": 6,
      "multiplicity": 0,
      "default_flow": 0.6,
      "vulnerability": {
        "name": "56",
        "controls": {
        "ScDb":{}
        }
      }
    }
   ]
}

=== przemub/cysectool/doc/templates/5_MITRE.json
{
  "name": "ClearSCADA second try",
  "controls": {},
  "vertices": [
    "The Internet",
    "Home PC or laptop",
    "Corporate thin client",
    "Vendor software",
    "Field laptop",
    "Site machine",
    "Test system",
    "ViewX",
    "WebX",
    "Control system",
    "File server"
  ],
  "edges": [
    {
      "source": 0,
      "target": 1,
      "default_flow": 0.9,
      "vulnerability": {
        "name": "Spearphishing Attachment",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0865"
    },
    {
      "source": 0,
      "target": 1,
      "default_flow": 0.6,
      "vulnerability": {
        "name": "Drive-by Compromise",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0817"
    },
    {
      "source": 0,
      "target": 2,
      "default_flow": 0.9,
      "vulnerability": {
        "name": "Spearphishing Attachment",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0865"
    },
    {
      "source": 0,
      "target": 2,
      "default_flow": 0.6,
      "vulnerability": {
        "name": "Drive-by Compromise",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0817"
    },
    {
      "source": 0,
      "target": 3,
      "default_flow": 0.3,
      "vulnerability": {
        "name": "Supply Chain Compromise",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 0,
      "target": 4,
      "default_flow": 0.2,
      "vulnerability": {
        "name": "Replication Through USB",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0847"
    },
    {
      "source": 3,
      "target": 2,
      "default_flow": 1,
      "vulnerability": {
        "name": "Infection via vendor",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 3,
      "target": 6,
      "default_flow": 1,
      "vulnerability": {
        "name": "Deployed for testing",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 6,
      "target": 4,
      "default_flow": 1,
      "vulnerability": {
        "name": "Deployed for production",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 6,
      "target": 5,
      "default_flow": 1,
      "vulnerability": {
        "name": "Deployed for production",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 6,
      "target": 7,
      "default_flow": 1,
      "vulnerability": {
        "name": "Deployed for production",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0862"
    },
    {
      "source": 5,
      "target": 9,
      "default_flow": 1,
      "vulnerability": {
        "name": "Exercise full control",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Impact"
    },
    {
      "source": 7,
      "target": 9,
      "default_flow": 1,
      "vulnerability": {
        "name": "Exercise full control",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Impact"
    },
    {
      "source": 8,
      "target": 9,
      "default_flow": 0.5,
      "vulnerability": {
        "name": "Exercise limited control",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Impact"
    },
    {
      "source": 1,
      "target": 8,
      "default_flow": 0.3,
      "vulnerability": {
        "name": "(temporary)",
        "controls": {}
      }
    },
    {
      "source": 0,
      "target": 10,
      "default_flow": 0.3,
      "vulnerability": {
        "name": "External access to SMB",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0822"
    },
    {
      "source": 0,
      "target": 5,
      "default_flow": 0.2,
      "vulnerability": {
        "name": "Wireless Compromise",
        "controls": {}
      },
      "url": "https://collaborate.mitre.org/attackics/index.php/Technique/T0860"
    }
  ]
}

=== przemub/cysectool/doc/templates/3_DVWA.json
{
  "name": "DVWA",
  "controls": {
    "Pn": {
      "name": "Pentesting",
      "level_name": [
        "Low",
        "Medium",
        "High"
      ],
      "cost": [
        3,
        5,
        10
      ],
      "ind_cost": [
        1,
        2,
        4
      ],
      "flow": [
        0.7,
        0.4,
        0.1
      ]
    },
    "Sc": {
      "name": "Secure configuration",
      "level_name": [
        "Low",
        "Medium",
        "High"
      ],
      "cost": [
        2,
        4,
        7
      ],
      "ind_cost": [
        1,
        1,
        2
      ],
      "flow": [
        0.7,
        0.4,
        0.1
      ]
    },
    "Pw": {
      "name": "Password policy",
      "level_name": [
        "Basic",
        "Strong"
      ],
      "cost": [
        1,
        2
      ],
      "ind_cost": [
        2,
        5
      ],
      "flow": [
        0.6,
        0.3
      ]
    },
    "A2": {
      "name": "Two-factor authentication",
      "level_name": [
        "Implemented"
      ],
      "cost": [
        4
      ],
      "ind_cost": [
        7
      ],
      "flow": [
        0.1
      ]
    },
    "Ex": {
      "name": "External firewall",
      "level_name": [
        "Basic",
        "Strong",
        "VPN"
      ],
      "cost": [
        3,
        5,
        6
      ],
      "ind_cost": [
        1,
        3,
        8
      ],
      "flow": [
        0.7,
        0.3,
        0.1
      ]
    },
    "In": {
      "name": "Internal firewall",
      "level_name": [
        "Basic",
        "Strong"
      ],
      "cost": [
        3,
        5
      ],
      "ind_cost": [
        1,
        3
      ],
      "flow": [
        0.7,
        0.3
      ]
    },
    "Vt": {
      "name": "Virtualisation / Containerisation",
      "level_name": [
        "Implemented"
      ],
      "cost": [
        5
      ],
      "ind_cost": [
        3
      ],
      "flow": [
        0.1
      ]
    },
    "Ed": {
      "name": "User education",
      "level_name": [
        "Online courses",
        "Attack simulations",
        "Strongly monitored policies"
      ],
      "cost": [
        2,
        4,
        6
      ],
      "ind_cost": [
        4,
        6,
        10
      ],
      "flow": [
        0.8,
        0.6,
        0.3
      ]
    }
  },
  "vertices": [
    "start",
    "PHP script",
    "admin panel",
    "database",
    "web user",
    "root",
    "ddos",
    "machine"
  ],
  "edges": [
    {
      "source": 0,
      "target": 2,
      "default_flow": 0.8,
      "vulnerability": {
        "name": "Brute force (login form)",
        "controls": {
          "Pw": {},
          "A2": {},
          "Ex": {}
        }
      }
    },
    {
      "source": 0,
      "target": 2,
      "default_flow": 0.5,
      "vulnerability": {
        "name": "Cross Site Request Forgery",
        "controls": {
          "Pn": {},
          "Ed": {}
        }
      }
    },
    {
      "source": 2,
      "target": 4,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "Command injection",
        "controls": {
          "Pn": {}
        }
      }
    },
    {
      "source": 2,
      "target": 4,
      "default_flow": 0.4,
      "vulnerability": {
        "name": "File inclusion (remote PHP script injection)",
        "controls": {
          "Pn": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 2,
      "target": 1,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "File upload (PHP script)",
        "controls": {
          "Pn": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 1,
      "target": 4,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "File inclusion (local PHP script injection)",
        "controls": {
          "Pn": {}
        }
      }
    },
    {
      "source": 2,
      "target": 6,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "File inclusion (self-inclusion)",
        "controls": {
          "Pn": {}
        }
      }
    },
    {
      "source": 2,
      "target": 6,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "File upload (DDOS)",
        "controls": {
          "Pn": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 0,
      "target": 3,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "SQL injection",
        "controls": {
          "Pn": {}
        }
      }
    },
    {
      "source": 0,
      "target": 3,
      "default_flow": 0.7,
      "vulnerability": {
        "name": "Brute force (on the database)",
        "controls": {
          "Ex": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 3,
      "target": 2,
      "default_flow": 1,
      "vulnerability": {
        "name": "Credentials change in the database",
        "controls": {
          "A2": {}
        }
      }
    },
    {
      "source": 3,
      "target": 4,
      "default_flow": 0.5,
      "vulnerability": {
        "name": "SQL shellcode",
        "controls": {
          "Sc": {}
        }
      }
    },
    {
      "source": 4,
      "target": 5,
      "default_flow": 1,
      "vulnerability": {
        "name": "Web user -> Root",
        "controls": {
          "In": {},
          "Sc": {}
        }
      }
    },
    {
      "source": 5,
      "target": 7,
      "default_flow": 1,
      "vulnerability": {
        "name": "Root -> Machine",
        "controls": {
          "Vt": {}
        }
      }
    }
  ]
}
